query SatReportContent($locale: I18NLocaleCode) {
  satReport(locale: $locale) {
    data {
      attributes {
        satReportIntro {
          data {
            attributes {
              title
              copyright
              background {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
            }
          }
        }
        satReportGreeting {
          data {
            attributes {
              title
              subtitle
              details
              actionButton {
                label
              }
              background {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
              icon {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
            }
          }
        }
        satReportGraph {
          data {
            attributes {
              title
              subtitle
              anchorText
              image {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
            }
          }
        }
        satReportQualification {
          data {
            attributes {
              title
              subtitle
              image {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
              qualificationData {
                data {
                  attributes {
                    title
                    description
                    category
                  }
                }
              }
            }
          }
        }
        satReportFarewell {
          data {
            attributes {
              title
              subtitle
              details
              actionButton {
                label
              }
              background {
                data {
                  attributes {
                    url
                    alternativeText
                    caption
                  }
                }
              }
            }
          }
        }
        satReportInformation {
          data {
            attributes {
              title
              subtitle
              informationTitle
              leftInformation
              rightInformation
            }
          }
        }
      }
    }
  }
}
