query orgDashboard($locale: I18NLocaleCode) {
  orgDashboard(locale: $locale) {
    data {
      attributes {
        coacheesTitle
        coachingSessionsTitle
        disableButton {
          label
        }
        datatable {
          data {
            attributes {
              nameColumnLabel
              emailColumnLabel
              positionColumnLabel
              statusColumnLabel
              coachColumnLabel
              signupColumnLabel
              actionsColumnLabel
              statusCodeNames {
                registrationStatus
                label
              }
            }
          }
        }
        graphDevelopmentArea {
          data {
            attributes {
              title
              subtitle
              description
              titleStrengths
              titleWeaknesses
              developmentAreas {
                label
                color
                icon
                developmentAreas
              }
            }
          }
        }
        graphFocusArea {
          data {
            attributes {
              title
              description
              focusAreasName {
                label
                color
                icon
                codeName
              }
            }
          }
        }
        graphTimeLine {
          data {
            attributes {
              title
              numberSessionsText
              buttonPeriod {
                label
                href
              }
            }
          }
        }
      }
    }
  }
}
