query orgDashboard($locale: I18NLocaleCode) {
  orgDashboard(locale: $locale) {
    data {
      attributes {
        coacheesTitle
        coachingSessionsTitle
        editCoaheeTitle
        inviteCoacheeTitle
        invalidEmailMessage
        errorMessage
        inviteButton {
          label
        }
        datatable {
          data {
            attributes {
              nameColumnLabel
              emailColumnLabel
              positionColumnLabel
              statusColumnLabel
              coachColumnLabel
              signupColumnLabel
              actionsColumnLabel
              statusCodeNames {
                registrationStatus
                label
              }
            }
          }
        }
        confirmDeletion {
          data {
            attributes {
              title
              message
              confirmButton {
                label
              }
              denyButton {
                label
              }
            }
          }
        }
        coacheeForm {
          data {
            attributes {
              nameInput {
                label
              }
              emailInput {
                label
              }
              positionInput {
                label
              }
              activeCheckLabel
              suspendCheckLabel
              adminCheckLabel
              canViewCheckLabel
              saveButton {
                label
              }
            }
          }
        }
        graphDevelopmentArea {
          data {
            attributes {
              title
              subtitle
              description
              titleStrengths
              titleWeaknesses
              developmentAreas {
                label
                color
                icon
                developmentAreas
              }
            }
          }
        }
        graphFocusArea {
          data {
            attributes {
              title
              description
              focusAreasName {
                label
                color
                icon
                codeName
              }
            }
          }
        }
        graphSatisfaction {
          data {
            attributes {
              title
              description
            }
          }
        }
        graphTimeLine {
          data {
            attributes {
              title
              numberSessionsText
              buttonPeriod {
                label
                href
              }
            }
          }
        }
      }
    }
  }
}
