query GetCoachDashboardContent($locale: I18NLocaleCode) {
  coachDashboard(locale: $locale) {
    data {
      attributes {
        allCoacheesLabel
        allTabLabel
        summaryTabLabel
        summaryCategories {
          label
          value
          key
        }
      }
    }
  }
}
