query collaboratorAdd($locale: I18NLocaleCode) {
  collaboratorAdd(locale: $locale) {
    data {
      attributes {
        fillFields
        validEmail
        emptyMessage
        status {
          label
          value
        }
        nameColumn
        emailColumn
        form {
          data {
            attributes {
              title
              subtitle
              input1
              input2
              input3
              input4
              button {
                label
              }
            }
          }
        }
      }
    }
  }
}
