query collaboratorAdd($locale: I18NLocaleCode) {
  collaboratorAdd(locale: $locale) {
    data {
      attributes {
        title
        subtitle
        fillFields
        validEmail
        emptyMessage
        status {
          label
          value
        }
        nameColumn
        emailColumn
        nameInput {
          placeholder
        }
        positionInput {
          placeholder
        }
        emailInput {
          placeholder
        }
        submitButton {
          label
        }
      }
    }
  }
}
