query getOrganizationProfile {
  getOrganizationProfile {
    id
    name
    owner {
      id
      name
    }
    coachees {
      id
      position
      canViewDashboard
      isActive
      isAdmin
      registrationStatus
      user {
        id
        name
        email
        createdAt
      }
      assignedCoach {
        profilePicture {
          key
          location
        }
        user {
          name
        }
      }
    }
  }
}
