query organizationSteps($locale: I18NLocaleCode) {
  organizationSteps(locale: $locale) {
    data {
      attributes {
        steps {
          label
          value
        }
        becomeCoacheeLabel {
          label
          value
        }
      }
    }
  }
}
