query getOrganizationCoacheesCoachingSessionTimeline($period: String!) {
  getOrganizationCoacheesCoachingSessionTimeline(period: $period) {
    labels
    datasets {
      label
      data
    }
  }
}
