query GetCoacheeDetailContent($locale: I18NLocaleCode) {
  coacheeDetail(locale: $locale) {
    data {
      attributes {
        notesTitle
        historyLabel
        evaluationsLabel
        evaluationTitle
        seeMoreButton {
          label
        }
        testButton {
          label
        }
        watchButton {
          label
        }
        editButton {
          label
        }
        coacheeCard {
          data {
            attributes {
              accordingToLabel
              organizationLabel
              signupFromLabel
              coacheeFromLabel
              messageButton {
                label
              }
            }
          }
        }
        editor {
          data {
            attributes {
              placeholderNote
              saveButton {
                label
              }
            }
          }
        }
      }
    }
  }
}
