query GetCoachDashboardContent($locale: I18NLocaleCode) {
  coacheeCards(locale: $locale) {
    data {
      attributes {
        accordingToLabel
        testLabel
        organizationLabel
        signupFromLabel
        coacheeFromLabel
        messageButton {
          label
        }
        developmentAreas {
          label
          developmentAreas
        }
      }
    }
  }
}
