export const userRoles = {
  STAFF: 'STAFF',
  COACH: 'COACH',
  COACHEE: 'COACHEE',
  SUPER_USER: 'SUPER_USER',
  COACHEE_ADMIN: 'COACHEE_ADMIN',
  COACHEE_OWNER: 'COACHEE_OWNER',
}

export const coacheeRegistrationStatus = {
  COACH_APPOINTMENT_PENDING: 'COACH_APPOINTMENT_PENDING',
  COACH_SELECTION_PENDING: 'COACH_SELECTION_PENDING',
  REGISTRATION_COMPLETED: 'REGISTRATION_COMPLETED',
  INVITATION_PENDING: 'INVITATION_PENDING',
  SAT_PENDING: 'SAT_PENDING',
}
