query collaboratorAdd {
   collaboratorAdd{
    data{
      attributes{
        fillFields
        validEmail
        emptyMessage
        status{
          label
          value
        }
        column1
        column2
        registration{
          data{
            attributes{
              title
              subtitle
              input1
              input2
              input3
              input4
              button{
                label
              }
            }
          }
        }
      }
    }
  }
}