query GetUserById($id: Int!) {
  findUserById(id: $id) {
    role
    name
    isStaff
    isActive
    languages
    isVerified
    isSuperUser
    coach {
      id
      profilePicture {
        key
        filename
        location
      }
    }
    coachee {
      id
      profilePicture {
        key
        filename
        location
      }
    }
    testResults {
      id
    }
    organization {
      id
      profilePicture {
        key
        filename
        location
      }
    }
    postsProgress {
      id
    }
    favoritesPosts {
      id
    }
  }
}
