query LoginContent($locale: I18NLocaleCode) {
  userRegister(locale: $locale) {
    data {
      attributes {
        title
        firstNameInput {
          placeholder
        }
        lastNameInput {
          placeholder
        }
        emailInput {
          placeholder
        }
        passwordInput {
          placeholder
        }
        submitButton {
          label
        }
        passwordSuggestion {
          data {
            attributes {
              promptLabel
              weakLabel
              mediumLabel
              strongLabel
              fillFieldsLabel
              suggestionList {
                label
                value
              }
            }
          }
        }
      }
    }
  }
}
