query getOrganizationProfileContent($locale: I18NLocaleCode) {
  orgProfile(locale: $locale) {
    data {
      attributes {
        title
        aboutLabel
        subscriptionLabel
        paymentMethodLabel
        changePasswordLabel
        creditCardLabel
        updatePlanButton {
          label
        }
        submitButton {
          label
        }
        cardPlans {
          data {
            attributes {
              header {
                label
                value
              }
              items {
                label
                check
              }
              button {
                label
              }
            }
          }
        }
      }
    }
  }
}
