query GetCoachAppointments($id: Int!) {
  findCoachAgendaById(id: $id) {
    coachAppointments {
      id
      remarks
      endDate
      startDate
      accomplished
      coacheeConfirmation
      coachingSession {
        id
      }
    }
  }
}
