query GetAssignedCoachees {
  getCoachProfile {
    assignedCoachees {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
        coachingSession {
          id
        }
      }
    }
  }

  getCoachDashboardData {
    coacheesWithoutRecentActivity {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
        coachingSession {
          id
        }
      }
    }
    coacheesWithUpcomingAppointments {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
        coachingSession {
          id
        }
      }
    }
    coacheesRecentlyRegistered {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
        coachingSession {
          id
        }
      }
    }
  }
}
