query FindAgendaByCoachId {
  getCoachProfile {
    coachAgenda {
      id
      outOfService
      availabilityRange {
        monday {
          from
          to
        }
        tuesday {
          from
          to
        }
        wednesday {
          from
          to
        }
        thursday {
          from
          to
        }
        friday {
          from
          to
        }
        saturday {
          from
          to
        }
        sunday {
          from
          to
        }
      }
    }
  }
}
