query GetAssignedCoachees($id: Int!) {
  findCoachById(id: $id) {
    assignedCoachees {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
      }
    }
  }

  getCoachDashboardData {
    coacheesWithoutRecentActivity {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
      }
    }
    coacheesWithUpcomingAppointments {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
      }
    }
    coacheesRecentlyRegistered {
      id
      profilePicture {
        key
        location
      }
      user {
        id
        name
        createdAt
      }
      dimensionAverages {
        base
        average
        dimension
      }
      organization {
        id
        name
      }
      coachAppointments {
        id
        startDate
        accomplished
        coachConfirmation
        coacheeConfirmation
      }
    }
  }
}
