query GetCoachById($id: Int!) {
  findCoachById(id: $id) {
    bio
    isActive
    phoneNumber
    profileVideo {
      key
      filename
      location
    }
    profilePicture {
      key
      filename
      location
    }
    user {
      id
      name
    }
    coachingAreas {
      id
      name
      codename
      description
      coverPicture
    }
  }
}
