query UserProfileContent($locale: I18NLocaleCode) {
  userProfile(locale: $locale) {
    data {
      attributes {
        title
        firstNameInput {
          placeholder
        }
        lastNameInput {
          placeholder
        }
        emailInput {
          placeholder
        }
        positionInput {
          placeholder
        }
        changePasswordButton {
          label
        }
        saveButton {
          label
        }
      }
    }
  }
}
