query getCoacheeProfile {
  getCoacheeProfile {
    coachAppointments {
      startDate
      accomplished
      coachConfirmation
      coachingSession {
        id
      }
    }
    assignedCoach {
      bio
      isActive
      phoneNumber
      profileVideo {
        key
        location
      }
      profilePicture {
        key
        location
      }
      user {
        id
        name
      }
      coachingAreas {
        id
        name
        codename
        description
        coverPicture
      }
    }
  }
}
