query GetAgendaByCoacheeId {
  getCoacheeProfile {
    assignedCoach {
      id
      coachAgenda {
        id
      }
    }
    coachAppointments {
      id
      remarks
      endDate
      startDate
      accomplished
      coachConfirmation
      coacheeConfirmation
      coachingSession {
        id
      }
    }
  }
}
