query GetAgendaByCoacheeId($id: Int!) {
  findCoacheeById(id: $id) {
    assignedCoach {
      id
    }
    coachAppointments {
      id
      accomplished
      coacheeConfirmation
      startDate
      endDate
      remarks
    }
  }
}
