query GetCoacheeById($id: Int!) {
  findCoacheeById(id: $id) {
    id
    bio
    position
    isActive
    aboutPosition
    registrationStatus
    coacheeEvaluations {
      id
      evaluation
    }
    profilePicture {
      key
      location
    }
    user {
      id
      name
    }
    organization {
      id
      name
    }
    dimensionAverages {
      base
      average
      dimension
    }
  }
}
