query GetCoacheeById($coacheeId: Int!) {
  findCoacheeById(coacheeId: $coacheeId) {
    id
    bio
    invited
    isAdmin
    position
    isActive
    phoneNumber
    aboutPosition
    canViewDashboard
    invitationAccepted
    registrationStatus
    profilePicture {
      key
      location
    }
    user {
      id
      name
    }
    organization {
      id
      name
    }
    coachingAreas {
      name
      codename
    }
    assignedCoach {
      id
    }
  }
}
