query GetCoacheeById($id: Int!) {
  findCoacheeById(id: $id) {
    id
    bio
    invited
    isAdmin
    position
    isActive
    phoneNumber
    aboutPosition
    profilePicture
    canViewDashboard
    invitationAccepted
    registrationStatus
    user {
      id
      name
    }
    organization {
      id
      name
    }
    coachingAreas {
      name
      codename
    }
    assignedCoach {
      id
    }
  }
}
