query GetCoacheeProfile {
  getCoacheeProfile {
    id
    bio
    invited
    isAdmin
    position
    isActive
    phoneNumber
    aboutPosition
    profilePicture {
      filename
    }
    canViewDashboard
    invitationAccepted
    registrationStatus
    user {
      id
      name
    }
    organization {
      id
      name
    }
    coachingAreas {
      name
      codename
    }
    assignedCoach {
      id
    }
  }
}
