query GetCoacheeProfile {
  getCoacheeProfile {
    id
    bio
    invited
    isAdmin
    position
    isActive
    phoneNumber
    aboutPosition
    canViewDashboard
    invitationAccepted
    registrationStatus
    profilePicture {
      key
      location
    }
    dimensionAverages {
      base
      average
      dimension
    }
    user {
      id
      name
    }
    organization {
      id
      name
    }
    coachingAreas {
      name
      codename
    }
    assignedCoach {
      id
    }
    objectives {
      id
      icon
      title
      tasks{
        id
        title
        progress
      }
    }
  }
}
