query GetSuggestedCoaches {
  getRandomSuggestedCoaches {
    id
    rejected
    rejectionReason
    coaches {
      id
      bio
      profileVideo {
        key
        location
      }
      profilePicture {
        key
        location
      }
      user {
        name
      }
      coachingAreas {
        id
        name
      }
    }
  }
}
