query GetScheduleContent($locale: I18NLocaleCode!) {
  coacheeSchedule(locale: $locale) {
    data {
      attributes {
        title
        availabilityLabel
        submitButton {
          label
        }
        scheduleButton {
          label
        }
      }
    }
  }
}
