query choosePlan($locale: I18NLocaleCode) {
  choosePlan(locale: $locale) {
    data {
      attributes {
        currentPlan {
          label
          value
        }
        next {
          label
        }
        card_plans {
          data {
            attributes {
              header {
                label
                value
              }
              items {
                label
                check
              }
              button {
                label
              }
            }
          }
        }
      }
    }
  }
  payment(locale: $locale) {
    data {
      attributes {
        title
        submitButton {
          label
        }
        paymentMethods {
          data {
            attributes {
              paymentMethodLabel
              paymentMethod
              methodIcon {
                data {
                  attributes {
                    alternativeText
                    caption
                    url
                  }
                }
              }
              nameInput {
                placeholder
              }
              emailInput {
                placeholder
              }
              cardInput {
                placeholder
              }
              expireDateInput {
                placeholder
              }
              cvcInput {
                placeholder
              }
              dniInput {
                placeholder
              }
            }
          }
        }
      }
    }
  }
}
